import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/split.dart';
import 'package:intl/intl.dart';

class ExportService {
  Future<void> exportSplitsToPdf(List<Split> splits) async {
    final doc = pw.Document();
    final font = await PdfGoogleFonts.nunitoExtraLight();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text('Evenly - Split History', style: pw.TextStyle(font: font, fontSize: 24)),
            ),
            pw.SizedBox(height: 20),
            pw.Table.fromTextArray(
              context: context,
              headers: ['Date', 'Name', 'Items', 'Participants', 'Total'],
              data: splits.map((split) {
                final date = DateFormat('yyyy-MM-dd').format(split.createdAt);
                final total = split.items.fold<double>(0, (sum, item) => sum + item.price);
                
                return [
                  date,
                  split.name ?? 'Unnamed',
                  split.items.length.toString(),
                  split.participants.length.toString(),
                  '\$${total.toStringAsFixed(2)}',
                ];
              }).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
              cellAlignment: pw.Alignment.centerLeft,
            ),
            pw.SizedBox(height: 20),
            pw.Paragraph(text: "Generated by Evenly App"),
          ];
        },
      ),
    );

    await Printing.sharePdf(bytes: await doc.save(), filename: 'evenly_history.pdf');
  }
}
